<h3>Index Index action</h3>

<div id="lexemes">
	should be here
</div>

<script type="text/template" id="lexemeTemplate">
	<ul>
		<li><%= id %></li>
		<li><%= language %></li>
		<li><%= type %></li>
		<li><%= entry %></li>
	</ul>
</script>

<?php echo $this->headScript()
	->appendFile($this->basePath() . '/js/lexemes/models/lexeme.js')
	->appendFile($this->basePath() . '/js/lexemes/collections/lexicon.js')
	->appendFile($this->basePath() . '/js/lexemes/views/lexeme.js')
	->appendFile($this->basePath() . '/js/lexemes/views/lexicon.js')
	->appendFile($this->basePath() . '/js/lexemes/app.js')
; ?>