<header id="myLexiconHeader">
	<h3>myLexicon</h3>
</header>
<section id="lexicon">
	
</section>
<footer></footer>

<script type="text/javascript">
	var allLexemes = <?php echo $this->lexemes; ?>;
	var allMeanings = <?php echo $this->meanings; ?>;
</script>

<script type="text/template" id="newMeaning">
	<div id="newMeaning">
		<form action="#">
			<label for="targetType">Target Type: </label><input id="targetType" type="text" />
			<label for="targetEntry">Target Entry: </label><input id="targetEntry" type="text" />
			<label for="baseType">Base Type: </label><input id="baseType" type="text" />
			<label for="baseEntry">Base Entry: </label><input id="baseEntry" type="text" />
			<button id="submitNewMeaning">Add</button>
		</form>
	</div>
</script>

<script type="text/template" id="meaningsInfo">
	<div id="meaningsInfo">
		Count: <%= meaningCount %>
		<button id="toggleMeaningForm">Add Meaning</button>
	</div>
</script>

<script type="text/template" id="meaningTemplate">
	<ul class="meaningInfo">
		<li>Frequency: <%= frequency %></li>
		<li>Date Entered: <%= dateEntered %></li>
	</ul>
</script>

<script type="text/template" id="lexemeTemplate">
	<ul class="lexemeInfo">
		<li>Lexeme Language: <%= language %></li>
		<li>Lexeme Type: <%= type %></li>
		<li>Lexeme Entry: <%= entry %></li>
	</ul>
</script>

<?php 
echo $this->headLink()->prependStylesheet($this->basePath() . '/css/lexemes.css');

echo $this->headScript()
	->appendFile($this->basePath() . '/js/lexemes/functions.js')
	->appendFile($this->basePath() . '/js/lexemes/application.js')
	->appendFile($this->basePath() . '/js/lexemes/models/lexeme.js')
	->appendFile($this->basePath() . '/js/lexemes/models/meaning.js')
	->appendFile($this->basePath() . '/js/lexemes/collections/lexemes.js')
	->appendFile($this->basePath() . '/js/lexemes/collections/meanings.js')
	->appendFile($this->basePath() . '/js/lexemes/views/lexeme-view.js')
	->appendFile($this->basePath() . '/js/lexemes/views/meaning-view.js')
	->appendFile($this->basePath() . '/js/lexemes/views/lexemes-view.js')
	->appendFile($this->basePath() . '/js/lexemes/views/meanings-view.js')
	->appendFile($this->basePath() . '/js/lexemes/routers/router.js')
; ?>